# Generated by Django 3.2.12 on 2023-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browserGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='nickname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
