# Generated by Django 4.2 on 2023-05-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browserGame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='failed_document',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='failed_line',
            new_name='line',
        ),
    ]
