# Generated by Django 4.2 on 2023-05-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browserGame', '0002_alter_character_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='run_number',
            field=models.IntegerField(default=0),
        ),
    ]
