# Generated by Django 4.2 on 2023-05-02 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browserGame', '0002_rename_failed_document_log_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type_log',
            field=models.CharField(choices=[('INF', 'Information'), ('WAR', 'Warning'), ('ERR', 'Error'), ('FAT', 'Fatal'), ('SQL', 'SQL')], max_length=4),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
